### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by denniske** [Electrolytic/push-quickstart#1]
Hi, I have two questions:

1. Why does this app generate a new token on every start? Shouldn't it be the same token per device on every run?
2. Does electrolytic allow for notifications when the app is closed?

**Comment by moinism** [comment]
@denniske Sorry for the late response.

1. For now, this is due to a technical restriction. But we know its not ideal and we're towards making the token persistent for a user on same machine.
2. Not yet. [I've written]() about that can achieved though. Let me know if that doesn't help. In the meantime, we're also working on bringing that functionality as a built-in feature.

Please let me know if there're any other questions or suggestion. Thank you!

**Comment by denniske** [comment]
Okay for 1. I am just sending the new token to my server on every application start, so that it replaces the old one. And I have also already implemented minimizing/closing to tray icon similar to your solution. So everything should work fine.

**Comment by moinism** [comment]
@denniske Great! FYI, with the latest version of package, you can now use [Analytics](https://electrolytic.app/docs/analytics) and [Cloud Config](https://electrolytic.app/docs/configs) in the dashboard too. Give them a try.

**Comment by denniske** [comment]
I will take a look. Thx :)
